// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
import "./globals.css"
import type { Metadata, Viewport } from "next"

export const metadata: Metadata = {
  title: "Turo AI Labs — AI Automation & Agentic AI for Businesses",
  description:
    "Turo AI Labs builds AI-powered automation tools, agentic AI workflows, and smart solutions to help businesses work smarter, scale faster, and innovate without limits.",
  keywords: [
    "AI Automation",
    "Agentic AI",
    "Business AI Tools",
    "Smart Workflows",
    "AI Solutions",
    "Artificial Intelligence",
    "Turo AI Labs"
  ],
  openGraph: {
    title: "Turo AI Labs — AI Automation & Agentic AI for Businesses",
    description:
      "We build AI-powered automation tools, agentic AI workflows, and smart solutions to help businesses work smarter, scale faster, and innovate without limits.",
    url: "https://www.turoailabs.com",
    siteName: "Turo AI Labs",
    images: [
      {
        url: "/og-image.png", // <- place your preview image in public folder
        width: 1200,
        height: 630,
        alt: "Turo AI Labs — AI Automation & Agentic AI for Businesses",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Turo AI Labs — AI Automation & Agentic AI for Businesses",
    description:
      "We build AI-powered automation tools, agentic AI workflows, and smart solutions to help businesses work smarter, scale faster, and innovate without limits.",
    images: ["/og-image.png"],
  },
  icons: {
    icon: "/favicon.ico",
  },
}

export const viewport: Viewport = {
  themeColor: "#1e1b4b", // deep indigo for AI branding
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
